services:
  wallet-app:
    container_name: wallet-app
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      wallet-db:
        condition: service_healthy
    environment:
      - POSTGRES_URL=jdbc:postgresql://wallet-db:5432/wallet
      - POSTGRES_PASSWORD=wallet
      - POSTGRES_USER=wallet
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://wallet-db:5432/wallet
      - SPRING_LIQUIBASE_USER=wallet
      - SPRING_LIQUIBASE_PASSWORD=wallet
      - SPRING_LIQUIBASE_change-log=db/main-changelog.xml

  wallet-db:
    image: postgres:16.1
    container_name: wallet-db
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=wallet
      - POSTGRES_USER=wallet
      - POSTGRES_DB=wallet
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    restart: unless-stopped
